### ISSUE TITLE
Remove explicit babel-runtime dependency from @iov/ledger-bns

### ISSUE THREAD

**Issue by webmaster128** [iov-one/iov-ledger-bns#1]
Currently required due to https://github.com/LedgerHQ/ledgerjs/issues/211

**Comment by webmaster128** [comment]
Caller code is responsible for creating the transport now. Both `@ledgerhq/hw-transport-node-hid` and `@ledgerhq/hw-transport-webusb` need the `regenerator-runtime` dependency at runtime, which is only a small subset of `babel-polyfill`.

**Comment by davepuchyr** [comment]
Close via https://github.com/iov-one/iov-ledger-bns/commit/7c580e583ab9b9091433f7b200158418afd41469.
