### ISSUE TITLE
Connect to ledger in web

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/iov-ledger-bns#3]
* Update iov-ledger-bns
* Verify transport that works in web (not node-hid)
* Make karma tests that work locally (same tests that are now, just run them in the browser)

**Comment by webmaster128** [comment]
In https://github.com/iov-one/ledger-iov-js we see example integration code for `hw-transport-node-hid`, `hw-transport-u2f` and `hw-transport-webusb`. U2F works in Firefox and Chrome, `hw-transport-webusb` seems to be Chrome only at the moment. Given that U2F in extension is still _wontfix_, we'll give WebUSB a try.
