### ISSUE TITLE
Rename LedgerSimpleAddressWallet

### ISSUE THREAD

**Issue by webmaster128** [iov-one/iov-ledger-bns#5]
LedgerSimpleAddressWallet does not use the deprecated "simple address" derivation anymore and the name should reflect that.

Possible options:
1. LedgerIovWallet
2. IovLedgerWallet
3. ideas?

**Comment by willclarktech** [comment]
@webmaster128 How specific is it to IOV? Our other wallets are named eg `Ed25519HdWallet` or `Slip10Wallet`. Could we name this `LedgerWallet`?

**Comment by webmaster128** [comment]
@willclarktech the Ledger wallet will only be able to connect to the IOV Ledger app. So it can be used for IOV testnet and IOV mainnet only. Also in `LedgerSimpleAddressWallet.createIdentity` we only pass an address index, which which will translate to the IOV HD path `m/44'234'/index`.

**Comment by willclarktech** [comment]
OK, then my preference is for `IovLedgerWallet`.

**Comment by webmaster128** [comment]
Sounds good
